version: '3.5'

networks:
  app_network:
    driver: bridge

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    networks:
      - app_network
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres
    volumes:
      - pg-volume:/var/lib/postgresql/data
    ports:
      - '${PORT_POSTGRES}:${PORT_POSTGRES}'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_network
    container_name: nest-app
    environment:
      - PORT=${PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src

volumes:
  pg-volume:

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db
